### ISSUE TITLE
Las pruebas unitarias fallan

### ISSUE THREAD

**Issue by fgonzalezc** [organizacion-sesion-3-fgonzalezc/sesion6-travis-heroku#1]
Hola @pedroprieto,

he estado modificando el proyecto que nos pasaste como ejemplo. Y mientras lo pruebo desde el navegador todo responde como debería. El problema lo tengo con las pruebas unitarias, que no hay forma de pasarlas.

Cuando lo ejecuto en local:
```
pegaso:sesion6-travis-heroku fragonca$ vendor/phpunit/phpunit/phpunit tests
PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in /Users/fragonca/Dropbox/Cursos/CEFIRE/Gestión de la tarea docente con GitHub/Tema06/sesion6-travis-heroku/vendor/phpunit/phpunit/src/Util/Getopt.php on line 45

Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /Users/fragonca/Dropbox/Cursos/CEFIRE/Gestión de la tarea docente con GitHub/Tema06/sesion6-travis-heroku/vendor/phpunit/phpunit/src/Util/Getopt.php on line 45
PHPUnit 4.4.5 by Sebastian Bergmann.

F

Time: 102 ms, Memory: 6.00MB

There was 1 failure:

1) RootTest::rootGet
Failed asserting that 'index' is identical to null.

/Users/fragonca/Dropbox/Cursos/CEFIRE/Gestión de la tarea docente con GitHub/Tema06/sesion6-travis-heroku/tests/RootTest.php:30

FAILURES!
Tests: 1, Assertions: 2, Failures: 1.
pegaso:sesion6-travis-heroku fragonca$
```

Me he dado cuenta luego de que debería fallar en la línea 32 de `RootTest.php` porque no he cambiado el número de links que envía la colección, pero no en la 30...

Y tampoco logro que pase las pruebas de Travis. Falla también en la línea 30.

¿Tienes alguna idea de qué puede estar pasando? No conozco demasiado ni Slim ni PHPUnit, así que tampoco sé muy bien lo que he podido estropear.

Por cierto, tu proyecto, sin modificar, me pasa las pruebas unitarias a la perfección.

**Comment by pedroprieto** [comment]
Hola Francisco,
Te he contestado vía comentario en el commit. El problema era una coma que te faltaba.

Efectivamente, también te fallará hasta que cambies el número de links de 4 a 5.

Un saludo!

**Comment by fgonzalezc** [comment]
Muchas gracias, Pedro!
